name: android_pip
description: A Picture-In-Picutre mode plugin for Android, allowing developers to easily provide PIP capabilities in their app, with support for PIP callbacks.
repository: https://github.com/harshitverma209/android_pip
homepage: https://github.com/harshitverma209/android_pip
version: 2.0.1

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.thesparks.android_pip
        pluginClass: AndroidPIPModePlugin